### ISSUE TITLE
ordered/set fails on Java 11

### ISSUE THREAD

**Issue by cloojure** [clj-commons/ordered#45]
Hi - This works with Clojure 10 and Java 10, but fails for Java 11.  Stack trace:

Exception in thread "main" Syntax error compiling deftype* at (flatland/ordered/set.clj:12:1).
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: Must hint overloaded method: toArray
	at clojure.lang.Compiler$NewInstanceMethod.parse(Compiler.java:8496)

**Comment by jafingerhut** [comment]
What version of ordered/set are you using?  There was a commit made to fix this on 2018-Oct-02 here: https://github.com/clj-commons/ordered/commit/16d0bc972539f21de2aac52f9270382fbe580fbb

It appears those changes should be part of version 1.5.7 of this library: https://clojars.org/org.flatland/ordered

**Comment by cloojure** [comment]
Never mind.  Just saw that you had already fixed it.

**Comment by cloojure** [comment]
It was due to an outdated dependency from io.forward/yaml
